# Generated by Django 4.1.7 on 2023-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время удаления'),
        ),
    ]
